package persistence;
// Generated 25 sept. 2016 14:21:11 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 * @author <a href="mailto:sabrinee.ayachi@gmail.com">Sabrine AYACHI</a>
 */
public class Client  implements java.io.Serializable {


     private int idclient;
     private String nom;
     private String prenom;
     private String adresse;

    public Client() {
    }

	
    public Client(int idclient) {
        this.idclient = idclient;
    }
    public Client(int idclient, String nom, String prenom, String adresse) {
       this.idclient = idclient;
       this.nom = nom;
       this.prenom = prenom;
       this.adresse = adresse;
    }
   
    public int getIdclient() {
        return this.idclient;
    }
    
    public void setIdclient(int idclient) {
        this.idclient = idclient;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }




}


