package persistence;
// Generated 25 sept. 2016 14:21:11 by Hibernate Tools 3.4.0.CR1



/**
 * Users generated by hbm2java
 *
 * @author <a href="mailto:sabrinee.ayachi@gmail.com">Sabrine AYACHI</a>
 */
public class Users  implements java.io.Serializable {


     private UsersId id;
     private String role;

    public Users() {
    }

	
    public Users(UsersId id) {
        this.id = id;
    }
    public Users(UsersId id, String role) {
       this.id = id;
       this.role = role;
    }
   
    public UsersId getId() {
        return this.id;
    }
    
    public void setId(UsersId id) {
        this.id = id;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


