package persistence;
// Generated 25 sept. 2016 14:21:11 by Hibernate Tools 3.4.0.CR1



/**
 * UsersId generated by hbm2java
 *
 * @author <a href="mailto:sabrinee.ayachi@gmail.com">Sabrine AYACHI</a>
 */
public class UsersId  implements java.io.Serializable {


     private String username;
     private String passeword;

    public UsersId() {
    }

    public UsersId(String username, String passeword) {
       this.username = username;
       this.passeword = passeword;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPasseword() {
        return this.passeword;
    }
    
    public void setPasseword(String passeword) {
        this.passeword = passeword;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersId) ) return false;
		 UsersId castOther = ( UsersId ) other; 
         
		 return ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) )
 && ( (this.getPasseword()==castOther.getPasseword()) || ( this.getPasseword()!=null && castOther.getPasseword()!=null && this.getPasseword().equals(castOther.getPasseword()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         result = 37 * result + ( getPasseword() == null ? 0 : this.getPasseword().hashCode() );
         return result;
   }   


}


